# Generated by Django 2.2.2 on 2019-06-25 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(null=True, verbose_name=django.core.validators.MinLengthValidator(10, message='Favourite description should not be less than 10 characters'))),
                ('rank', models.IntegerField()),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='favouritesapi.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Data'), ('enum', 'Enum')], max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='favouritesapi.Favourite')),
            ],
        ),
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('new_value', models.TextField()),
                ('old_value', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_item', to='favouritesapi.Favourite')),
            ],
        ),
    ]
