# Generated by Django 2.2.2 on 2019-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favouritesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
