# Generated by Django 2.2.2 on 2019-06-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favouritesapi', '0002_category_category_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_count',
            new_name='favourite_count',
        ),
    ]
