# Generated by Django 2.2.2 on 2019-06-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favouritesapi', '0003_auto_20190626_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='favourite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='favouritesapi.Favourite'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='favouritesapi.Category'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='favourite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatas', to='favouritesapi.Favourite'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
