# Generated by Django 2.2.2 on 2019-06-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favouritesapi', '0004_auto_20190627_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='author',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='favourite',
            new_name='favourite_id',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='favourite',
            new_name='favourite_id',
        ),
    ]
